# Generated by Django 5.2.10 on 2026-01-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address_line1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_pincode",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
