# Generated by Django 5.2.10 on 2026-02-01 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedreport",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorysnapshot",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_snapshots",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productsalesmetric",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_metrics",
                to="products.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventorysnapshot",
            unique_together={("date", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="productsalesmetric",
            unique_together={("product", "date")},
        ),
    ]
